sudo: required
language: minimal
services:
- docker
script:
- docker/build.sh ${TRAVIS_BRANCH}
deploy:
- provider: script
  script: bash docker/publish_docker.sh ${TRAVIS_BRANCH}
  on:
    tags: true
- provider: script
  script: bash docker/publish_docker.sh ${TRAVIS_BRANCH} latest
  on:
    branch: master
env:
  global:
  - secure: iHiU+QIdm1ApXjlmcdnzCDeEkjcfhPLdrFjg73IFl19f7ZFlxDKdbx62y4ZMcFzNZ7KnHRYyFoQ0dQviC+ye1Acdgojm4URPxdXlNQf/u9OYnodkayoTJvqT6RP4FeqEh+TRtgXSWjlKJOF5cnL3iq5lvSR5XZ3J8K97EN7BzrmYUnINoSjbGxrsozplPLJWk2+/IkgokZcdGlcocUAVmIjhXGi7XDG/CgTlnNGC92AJWX4ytXD50/Iazq3Vkzfx2TjcN3hNxud+Xj7jlHq0E8snrreIH7mwE3hJizV4XH+POq4qP6/MqaiW68sB632vsGG8mB3ptwEVvpNR0SMKw3g+XdIWxZBcLc+vLn1FgY6fDyDHMGZibPMkltH7pY6u5fDy5XP3dsvWnDWMv1mLyHaZZE4LaDkUmLQ3b8D6e0zBwGKe11UhAbRNWREOJS6l/FCQdcNLEhB8NpQdVHUYIAzy52glWGJc2tfBWRFV7jMQaT8Da3JLR+rsKPVQuuvPfmXYBYh2abrjW25P87v17i90I1bUkU2JDB6vzZtkAm2W9QOLFE7hnyFzm9fxFpScwdwDKyLRpOanwmIUMEvtX4rrlLi2/VevDRmNyjXy0FpoQWc9aM9rFW99SQePWDh/QIYZctgrz9mlWhRiobx5e88R9GuoNS5GGKqlxYS4w9M=
  - secure: YjD870hsLbqW+sYic4z3Y0pzjB7pwGKR7H8YQbopf4xwhkwZu4/5lsf4Zpr6L+JHMGhLfW2YBr3cFiTQdlmRp65hKrg6WRvHJTC6x8FHuiI5X0m7jrPGElO1Z1HtrH+qWGoqMDKym3tDrnP71QKu1Zj4WryVQTTrCX4O0iQopJFJVFvtZGE04iHR4cXmWHJWyOgezZwN1jvwoAUe/MFQtshesSVSP0Xa6a4N5deqflo1WAvVxZeFb4RAcT5xp5nDWdxf4wyuOjY4q8XRLrbLqPTrezx1n7gceC4gFC1szwqJcVyOZQQoinnf1TjsRR7NVo+vxxBiZ8zVH7eprWT7Xdm+63NImV6FJb+Osyd95fessIUt4CxK2Gt6jWYbNe7cT24q/4n4HvHUxLVaN1GCrmnSPoC3gdwWMrKS1YaYTBcT3NiucJ6b2Q/3IosJhYFRoaSkaZ45pTKpj0gYokphHGh2KZJYrHkntum4nbzTStid5pVQxXQa5GjG2Isatea8k57D5NsG97UzOpHF0WHtAKsfCH7reifRNQbzN8CA/q7O1L1l7yVqZ/2jAAO19GWF8EgsKDlNXvPO2ThFN9JvIoUq0v2TkU3n36iXj7rehBFbRWjG+jzXNjp8sUm1p3jOm7hAE4F1w9PV/+Ptv4Yi+cqxb/dVam65+fLb/Et8krk=
